const tests = [
  "./api/dsl.test.mjs",
  "./api/data.test.mjs",
  "./api/public-contract.test.mjs",
  "./chart-renderer-dispatch.test.mjs",
  "./axis.test.mjs",
  "./layout/stack-align.test.mjs",
  "./layout/measurement-adapter.test.mjs",
  "./layout/render-output.test.mjs",
  "./layout/repeat-embed.test.mjs",
  "./layout/repeat-edge.test.mjs",
  "./layout/repeat-shared-domain.test.mjs",
  "./layout/image.test.mjs",
  "./container/sequence.test.mjs",
  "./container/grid.test.mjs",
  "./container/custom.test.mjs",
  "./mark/bar.test.mjs",
  "./mark/scatter.test.mjs",
  "./mark/bubble.test.mjs",
  "./mark/area.test.mjs",
  "./mark/line.test.mjs",
  "./mark/matrix.test.mjs",
  "./mark/box.test.mjs",
  "./mark/stream.test.mjs",
  "./mark/flow.test.mjs",
  "./mark/dumbbell.test.mjs",
  "./mark/pac.test.mjs",
  "./mark/pie.test.mjs",
  "./mark/validation.test.mjs",
  "./layout/text.test.mjs",
  "./dev-example.test.mjs",
  "./examples-runtime.test.mjs",
  "./package-metadata.test.mjs",
  "./types-definition.test.mjs",
  "./workflow.test.mjs",
  "./site/homepage.test.mjs",
  "./site/example-assets.test.mjs",
  "./site/example-card-style.test.mjs",
  "./site/example-preview-runner.test.mjs",
  "./site/code-block-style.test.mjs",
  "./site/docs-nav.test.mjs",
  "./site/docs-content.test.mjs",
  "./site/marks-docs.test.mjs",
  "./site/example-editor.test.mjs",
  "./site/example-snippet-sync.test.mjs",
  "./export/svg-dom-export.test.mjs",
  "./export/node-export.test.mjs",
];

for (const test of tests) {
  await import(test);
}

console.log("All tests passed");
