const tests = [
  "./api/dsl.test.mjs",
  "./api/data.test.mjs",
  "./api/public-contract.test.mjs",
  "./chart/renderer-dispatch.test.mjs",
  "./chart/axis.test.mjs",
  "./layout/stack-align.test.mjs",
  "./layout/stack-padding-inference.test.mjs",
  "./layout/stack-link.test.mjs",
  "./layout/measurement-adapter.test.mjs",
  "./layout/render-output.test.mjs",
  "./layout/root-render.test.mjs",
  "./layout/wrapper-box-model.test.mjs",
  "./layout/sizing-policy.test.mjs",
  "./layout/nested-composition-render.test.mjs",
  "./layout/node-ownership.test.mjs",
  "./layout/embed-slot.test.mjs",
  "./layout/repeat-embed.test.mjs",
  "./layout/repeat-edge.test.mjs",
  "./layout/repeat-shared-domain.test.mjs",
  "./layout/image.test.mjs",
  "./container/sequence.test.mjs",
  "./container/grid.test.mjs",
  "./container/custom.test.mjs",
  "./chart/bar.test.mjs",
  "./chart/scatter.test.mjs",
  "./chart/bubble.test.mjs",
  "./chart/area.test.mjs",
  "./chart/line.test.mjs",
  "./chart/matrix.test.mjs",
  "./chart/box.test.mjs",
  "./chart/stream.test.mjs",
  "./chart/flow.test.mjs",
  "./chart/dumbbell.test.mjs",
  "./chart/pac.test.mjs",
  "./chart/pie.test.mjs",
  "./chart/validation.test.mjs",
  "./layout/text.test.mjs",
  "./dev-example.test.mjs",
  "./examples-runtime.test.mjs",
  "./package-metadata.test.mjs",
  "./types-definition.test.mjs",
  "./workflow.test.mjs",
  "./site/homepage.test.mjs",
  "./site/example-registry.test.mjs",
  "./site/example-assets.test.mjs",
  "./site/example-card-style.test.mjs",
  "./site/example-preview-runner.test.mjs",
  "./site/code-block-style.test.mjs",
  "./site/docs-nav.test.mjs",
  "./site/docs-content.test.mjs",
  "./site/marks-docs.test.mjs",
  "./site/example-editor.test.mjs",
  "./site/example-snippet-sync.test.mjs",
];

for (const test of tests) {
  await import(test);
}

console.log("All tests passed");
