import assert from "node:assert/strict";
import * as api from "../../src/index.js";

const stableExports = [
  "GridContainer",
  "SequenceContainer",
  "assertLayoutNode",
  "chart",
  "crossJoin",
  "custom",
  "customContainer",
  "embed",
  "frame",
  "gridContainer",
  "image",
  "isLayoutNode",
  "loadCsvText",
  "numericColumns",
  "parseCsv",
  "repeat",
  "repeatX",
  "repeatY",
  "sequenceContainer",
  "stackX",
  "stackY",
  "tableColumns",
  "text",
  "validateChartConfig",
].sort();

assert.deepEqual(
  Object.keys(api).sort(),
  stableExports,
  "src/index.js should expose only the stable user-facing API",
);

[
  "AreaChartRenderer",
  "AxisRenderer",
  "BBox",
  "BarChartRenderer",
  "BoxPlotRenderer",
  "BubbleChartRenderer",
  "Chart",
  "Composition",
  "DirectionlessRepeat",
  "DumbbellChartRenderer",
  "Embedded",
  "FlowDiagramRenderer",
  "Frame",
  "GroupBarChartRenderer",
  "LayoutCalculator",
  "LayoutEngine",
  "LayoutRenderer",
  "LineChartRenderer",
  "MARK_DEFINITIONS",
  "MarkRenderer",
  "MatrixChartRenderer",
  "Node",
  "PieChartRenderer",
  "ProportionalAreaChartRenderer",
  "Repeat",
  "RepeatX",
  "RepeatY",
  "ScatterChartRenderer",
  "Stack",
  "StackBarChartRenderer",
  "StreamGraphRenderer",
  "renderComputedLayout",
].forEach((name) => {
  assert.ok(!(name in api), `src/index.js should not export ${name}`);
});
